#!/usr/bin/env python3
# Emit a header embedding each kernel source file as a NUL-terminated byte array,
# plus a {name, src} lookup table, so the binary carries its own kernels and a
# copied binary needs no cuda/ dir. Regenerated by the Makefile from the 4 files.
import sys
files = sys.argv[1:]
print("/* auto-generated by cuda/gen_embed.py (make); DO NOT EDIT.")
print("   Embeds the kernel source so the binary is self-contained. */")
tbl = []
for f in files:
    data = open(f, "rb").read()
    base = f.rsplit("/", 1)[-1]
    var = "k_embed_" + base.replace(".", "_").replace("-", "_")
    tbl.append((base, var))
    sys.stdout.write("static const char %s[]={" % var)
    sys.stdout.write(",".join(str(b) for b in data))
    sys.stdout.write(",0};\n")
print("static const struct { const char *name, *src; } g_embed_kernels[]={")
for base, var in tbl:
    print('  {"%s",%s},' % (base, var))
print("  {0,0}};")
